# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Lore
description: > # this means to ignore newlines until "baseurl:"
  Lore is a convention-driven framework for building React applications.
  It is built on Webpack, Redux and React-Router.

# Serving
baseurl: "" # the subpath of your site, e.g. /blog

# Conversion
markdown: kramdown
#kramdown:
#  input: GFM
#  syntax_highlighter: rouge

# Handling Reading
exclude: ["node_modules"]

# Custom
url: "http://www.lorejs.org" # the base hostname & protocol for your site
